### ISSUE TITLE
I'm wondering....

### ISSUE THREAD

**Issue by megadox** [DevExpress-Examples/how-to-add-a-control-based-document-e3912#1]
I'm wondering how to add a ToolTip to a BaseDocument.
I added a UserControl to a TabbedView. 
But I could not add the BaseDocument of the tabbedview.

**Comment by SvetlanaPN** [comment]
Hi, 

Please [submit a ticket to our Support Center](https://www.devexpress.com/Support/Center/Question/Create) and describe your scenario in greater detail. 
In particular, clarify there for what element you wish to show a tooltip and how this task relates to your last sentence.
